import type { Metadata } from 'next';
import { Saira } from 'next/font/google';

import StyledComponentsRegistry from '@/lib/registry';
import { GlobalStyles } from '@/styles/GlobalStyles';

const fontFamily = Saira({
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Eduardo Alves - Desenvolvedor',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/favicon.svg"
          type="image/x-icon"
        />
      </head>

      <body className={`${fontFamily.className}`}>
        <StyledComponentsRegistry>
          <GlobalStyles />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
